### ISSUE TITLE
[ERROR: action.script] 62:65: syntax error: Expected end of line but found property

### ISSUE THREAD

**Issue by emilras** [vitorgalvao/alfred-workflows#20] opened 2016-07-07 06:10 UTC
IncognitoClone has stopped working. I'm using Mac OS X 10.11.5 (15F34) and Alfred 3.0.2 [676].

**Comment by vitorgalvao** [comment] 2016-07-07 09:51
Cannot reproduce at all. Delete it and download it again. Deleting is important, to make sure Alfred does not save any changed that may have happened to it.

**Comment by emilras** [comment] 2016-07-07 10:36
Hmm. That didn't work. Seems to be a problem with AppleScript and Google Chrome (Version 51.0.2704.106)

![2016-07-07_12-34-58](https://cloud.githubusercontent.com/assets/1532192/16650586/3ce3617c-443f-11e6-9ea5-583bb392bd31.png)

Others have trouble with the active tab: http://www.alfredforum.com/topic/4435-pinboard-14-for-alfred-3-search-add-and-delete-bookmarks/page-3

**Comment by vitorgalvao** [comment] 2016-07-07 11:45
Still cannot reproduce, and I’m using the same Chrome version. You might want to try to reinstall Chrome.

Since this seems to be a localised problem, and a bug with Chrome, at that (i.e. something I cannot fix), will close this. It even works well with my install of Chrome Canary, so this it’s unlikely this change of behaviour is on purpose. You need to open a bug report on Chrome’s tracker.

**Closed by vitorgalvao** 2016-07-07 11:45 UTC
Labels: IncognitoClone

**Comment by emilras** [comment] 2016-07-07 12:52
Appreciate you looking into this. IncognitoClone is one of my most used workflows - thanks!

**Comment by vitorgalvao** [comment] 2016-07-07 14:50
Glad to know. If you find any details on this (like the Chrome team suggesting they will make this behave differently or marking as `wontfix`), please do let me know, so I can investigate further.

**Comment by emilras** [comment] 2016-07-07 14:55
@vitorgalvao I think I got it resolved. It appears that my Windows (via Parallels) version of Google Chrome was initiated instead of my mac version... I'm somewhat puzzled on why this behaviour suddenly have begun - I haven't noticed any changes/updates in my setup.

I have fixed the workflow by referencing the application name with some more specificity: 

`tell application "/Applications/Google Chrome.app"`

I have little experience with AppleScripts, so I don't know if this a good fix?

There is some background here: http://stackoverflow.com/questions/4956445/virtual-machine-browser-is-considered-by-the-applescript-if-parallels-are-instal

**Comment by vitorgalvao** [comment] 2016-07-07 15:12
Nice find. Good to know you got it fixed.

Yes, that is a good fix for your case. I won’t implement it in the workflow itself since by specifying a path more issues can occur (for people that install to atypical locations, which are more than the ones that use Parallels), but it’ll fix your case nicely.
