### ISSUE TITLE
Getting error in Hackerboard workflow

### ISSUE THREAD

**Issue by nikitavoloboev** [vitorgalvao/alfred-workflows#38] opened 2017-08-06 17:14 UTC
Updated the Hackerboard workflow and nothing showed. Here is what the debugger shows :  

```
2017-08-06 19:11:30][ERROR: input.scriptfilter] Code 1: /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:921:in `connect': SSL_connect returned=1 errno=0 state=SSLv2/v3 read server hello A: tlsv1 alert protocol version (OpenSSL::SSL::SSLError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:921:in `block in connect'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/timeout.rb:52:in `timeout'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:921:in `connect'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:862:in `do_start'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:851:in `start'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:313:in `open_http'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:709:in `buffer_open'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:210:in `block in open_loop'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:208:in `catch'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:208:in `open_loop'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:149:in `open_uri'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:689:in `open'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:34:in `open'
	from ./hackerboard:34:in `<main>'
```

I believe it was working perfectly well before the update. Not sure what changed.

Pinboard works well on the other hand.

**Comment by nikitavoloboev** [comment] 2017-08-06 17:19
Also, just curious, shouldn't the OneUpdater object be connected in this workflow? 

![2017-08-06 at 19 18](https://user-images.githubusercontent.com/6391776/29005451-1f2fd5a0-7adc-11e7-9541-ce1b06e52fb5.png)

Right now it is kind of isolated and never gets run I think.

**Comment by vitorgalvao** [comment] 2017-08-06 18:25
> Also, just curious, shouldn't the OneUpdater object be connected in this workflow?

No. It’s a Script Filter. That’s documented in OneUpdater’s README.

> Right now it is kind of isolated and never gets run I think.

It doesn’t run, but not because it isn’t connected. It doesn’t run because I forgot to add its Keyword. It’s fixed in the latest version, but that doesn’t matter much — it’s unlikely that Workflow will ever need an update.

But please don’t mix two completely unrelated things in the same issue.

---

As for the subject of the issue, the problem is related to the system Ruby. Pushed a workaround that I’ll revert after High Sierra is released.

**Closed by vitorgalvao** 2017-08-06 18:25 UTC
