### ISSUE TITLE
Bug report: CalmNotifications indicates focus mode is enabled when it  isn't

### ISSUE THREAD

**Issue by moderatoburrito** [vitorgalvao/alfred-workflows#147] opened 2022-02-22 09:45 UTC
#### Setup info

* Workflow name: CalmNotifications
* Workflow version: 21.9
* Alfred version: 4.6.3 [1285] (although the behaviour was the same with the Alfred version just before)
* macOS version: 12.2.1
* Architecture: M1

#### Description of issue

CalmNotifications erroneously detects focus mode being enabled when it isn't. I type "dnd" with focus mode disabled and CalmNotifications indicates that focus mode is on. In more detail, it says "Turn it off", with "Allow notification" below. Focus / do not disturb is definitely disable though. I expected to be offered the option to enable focus mode. 

If I hit the return key while Alfred shows "Turn it off", nothing happens as it is already off.

FWIW,  CalmNotifications used to work just fine. I am not sure what changed.

#### Debugger output

```
[11:40:27.380] CalmNotifications[[Script Filter](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.2A365EDD-C65D-4292-9F4F-D319A637AF49%3E3E435725-836B-4634-BF9F-B8DBADDDEABF)] Queuing argument ''
[11:40:28.496] CalmNotifications[[Script Filter](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.2A365EDD-C65D-4292-9F4F-D319A637AF49%3E3E435725-836B-4634-BF9F-B8DBADDDEABF)] Script with argv '' finished
[11:40:28.512] CalmNotifications[[Script Filter](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.2A365EDD-C65D-4292-9F4F-D319A637AF49%3E3E435725-836B-4634-BF9F-B8DBADDDEABF)] {"items":[{"title":"Turn it off","subtitle":"Allow notifications again","arg":"off","icon":{"path":"icon_alt.png"}}]}
[11:40:32.031] CalmNotifications[[Script Filter](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.2A365EDD-C65D-4292-9F4F-D319A637AF49%3E3E435725-836B-4634-BF9F-B8DBADDDEABF)] Processing complete
[11:40:32.034] CalmNotifications[[Script Filter](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.2A365EDD-C65D-4292-9F4F-D319A637AF49%3E3E435725-836B-4634-BF9F-B8DBADDDEABF)] Passing output 'off' to [Run Script](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.2A365EDD-C65D-4292-9F4F-D319A637AF49%3E4C30FC65-71BF-4EFE-94CC-B038B4D991CA)
[11:40:32.035] CalmNotifications[[Script Filter](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.2A365EDD-C65D-4292-9F4F-D319A637AF49%3E3E435725-836B-4634-BF9F-B8DBADDDEABF)] Passing output 'off' to [Run Script](alfredpreferences:workflows%3Eworkflow%3Euser.workflow.2A365EDD-C65D-4292-9F4F-D319A637AF49%3E5116FFE2-57F2-4B38-88EA-24FC77101347)
```

I have also tried deleting and reinstalling the workflow. Thanks for any help.

**Comment by vitorgalvao** [comment] 2022-02-22 13:08
I cannot reproduce the issue with the same versions as you. How soon before turning off DND are you checking? Because it can take a few seconds before macOS commits the changes necessary for the Workflow to know if DND is on or off.

For reference, the command CalmNotifications uses to check if DND is on (you can try it in a Terminal) is:

```
/usr/bin/defaults read com.apple.controlcenter 'NSStatusItem Visible FocusModes'
```

 `1` means on, `0` means off. If that number isn’t changing when you enable/disable DND, there’s something odd with your setup. Alternatively, keep in mind this Workflow only supports straight up DND, I don’t know how checking the status is affected by the new Focus features but that was never reported as an issue.

Because I cannot reproduce, there are no other reports, and the interaction is a single command, you’ll have to do the rest of the investigation yourself on what about your machine is odd or has changed.

**Comment by moderatoburrito** [comment] 2022-02-24 08:35
@vitorgalvao thanks so much for the response and the advice! Indeed, something odd is going on with my computer. When I run that command to query the status, it always reports `1` regardless of whether DND is enabled, or not.

I'll do some research when I have more time. I'm not sure I can face a reinstall though!

**Comment by vitorgalvao** [comment] 2022-02-24 21:48
Closing for now, but if you find anything else feel free to add here if you feel like it.

**Closed by vitorgalvao** 2022-02-24 21:48 UTC
