### ISSUE TITLE
WebScreenshot workflow broken on Big Sur

### ISSUE THREAD

**Issue by nikitavoloboev** [vitorgalvao/alfred-workflows#115] opened 2020-09-14 11:50 UTC
#### Setup info

* Workflow name: WebScreenshot
* Workflow version: 20.1
* Alfred version: 4.1.1
* macOS version: 11.0 Beta

#### Description of issue

Trying to use it, I get this error:

<img width="328" alt="image" src="https://user-images.githubusercontent.com/6391776/93082412-30f0ce00-f691-11ea-82bc-fbae18d6d5f6.png">

#### Debugger output

```
[13:50:17.117] Logging Started...
[13:50:17.907] WebScreenshot[Hotkey] Processing complete
[13:50:17.908] WebScreenshot[Hotkey] Passing output '' to Run Script
[13:50:21.230] STDERR: WebScreenshot[Run Script] execution error: Error: TypeError: undefined is not an object (evaluating '$.NSEvent.modifierFlags') (-2700)
[13:50:21.231] WebScreenshot[Run Script] Processing complete
[13:50:21.232] WebScreenshot[Run Script] Passing output '' to Run Script
```

**Comment by vitorgalvao** [comment] 2020-09-14 12:16
From the debugger output it looks like a problem with [Notificator](https://github.com/vitorgalvao/notificator), not WebScreenshot. That means more of my Workflows would be affected but also that the Workflows are themselves working.

Either way, I don’t install Apple beta OSs (their stable ones are buggy enough as it is) so I have no way to test for and fix this. It would require a lot of trial and error and back and forth.

Technically I could remove the offending code because it’s not essential to the notification. But it’s more likely that is caused by an Apple bug that will (or should) be fixed on the final release, so there’s effectively zero chance I’m going to spend any unpaid free time or sanity chasing it.

Regarding code I produce, macOS betas are not supported, not recommended, and installed at the user’s own risk. I may consider working pull requests, but issues are considered only if the bug is proven to be caused by a documented change in behaviour in macOS, not beta bugs.

**Closed by vitorgalvao** 2020-09-14 12:16 UTC
